#define USER_FOUND "00"
#define USER_NOT_FOUND "01"

#define PASSWORD_FALSE "10"
#define PASSWORD_REQUIRED "11"
#define USER_NAME_SHOULD_BE_SENT_FIRST "12"

#define USER_ALREADY_LOGINNED "20"

#define TRAINING_REQUEST_ACCEPTED "31"
#define TRAINING_REQUEST_DENIED "32"

#define TESTING_REQUEST_ACCEPTED "40"
#define TESTING_REQUEST_DENIED "41"

#define USER_UNAUTHORIZED_ACTION "50"

#define LOGIN_SUCCESSFUL "60"

#define LOGOUT_ACCEPTED "70"
#define LOGOUT_DENIED "71"
#define LOGOUT_INVALID "72"
#define LOGOUT_COMPULSORY "73"

#define SYNTAX_WRONG "80"

